export const SELECTED_CITY = 'SELECTED_CITY';
export const SELECT_CITY_FIELD_WARNING = 'SELECT_CITY_FIELD_WARNING';

export const SET_RESTAURANTS = 'SET_RESTAURANTS';
export const SET_RESTAURANTS_SUCCESS = 'SET_RESTAURANTS_SUCCESS';
export const SET_RESTAURANTS_FAILURE = 'SET_RESTAURANTS_FAILURE';

export const SET_SEARCH_BY_OPTION = 'SET_SEARCH_BY_OPTION';
export const SET_SEARCH_KEYWORD = 'SET_SEARCH_KEYWORD';

export const LOAD_LIST_OF_CITIES = 'LOAD_LIST_OF_CITIES';
